### ISSUE TITLE
Cannot receive multiple parallel packets by discovery broadcast

### ISSUE THREAD

**Issue by phonic** [MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp#11]
Hi there,

I've a scenario where I have to do a discovery broadcast to a dozens of devices (100 and more). Unfortunatley, the plugin seems to be in trouble with receiving the correct count of "answer"-packets. One-half of the packets is getting lost. The problem occurs on android, I did not test this behaviour on iPhone so far. 
Are there any suggestions to deal with? Is this plugin not recommend for such scenarios? 

Thank you in advance for any reply!

**Comment by bemasc** [comment]
UDP is not a reliable message transport.  Messages can be lost in transit.  Unless you have evidence that the loss rate with this plugin is much higher than with other UDP socket implementations, there is no bug here.
