### ISSUE TITLE
No support for setBroadcast

### ISSUE THREAD

**Issue by digitalcatnip** [MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp#7]
Hi,

It appears 'setBroadcast' is in the API documents but not in the actual API itself.  Do you know when this will be available?

https://developer.chrome.com/apps/sockets_udp#method-setBroadcast

**Comment by mmocny** [comment]
Those docs are for the "real" chrome apps platform for desktop/chromeos.

This plugin is an attempted port of that api, so some of those docs apply, but often they are out of sync.

`setBroadcast` is indeed not implemented in this plugin (I think it was added after this plugin was written), and there is no longer any active support for this plugin.  (See [this project status update](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/README.md#create-chrome-apps-for-mobile-using-apache-cordova))

**Comment by digitalcatnip** [comment]
Okay, thanks for the update.  Can you add a note to the readme that notes the plugin is no longer supported?

**Comment by ivan3619** [comment]
Hi,@digitalcatnip . I  have the same  trouble, that no support for setBroadcast . Do you resolve the question? Thanks a lot .

**Comment by digitalcatnip** [comment]
@ivan3619 I ended up forking a different project, adding the iOS support, and using that in my project.

**Comment by gregvis** [comment]
i've added setBroadcast for both iOS and Android in my fork...i'm hoping this will be merged with the main repo soon. 

In the meantime, you could add my fork instead of the main:
`cordova plugin add https://github.com/gregvis/cordova-plugin-chrome-apps-sockets-udp.git`

**Comment by agrieve** [comment]
I've merged in @gregvis's fix and published the plugin as v1.3.0
