### ISSUE TITLE
iOS receive doesn't work

### ISSUE THREAD

**Issue by Kobzol** [MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp#9]
I'm having problems with receiving UDP sockets on iOS.
I create a socket on iPhone, send a message, the other side receives it and sends a response to the phone's address (IP, port), but the callback registered with onReceive doesn't fire.
The same code works without problems on Android.
I tried setting the socket as persistent, that didn't help.
Is there anything extra that has to be done for this to work?

**Comment by oahziur** [comment]
Did you bind the port before sent the message?

**Comment by Kobzol** [comment]
I tried it both with and without binding the socket without send, neither worked.
If I bind the socket before send, it works (except for the receive), but it gives me an iOS error in the console saying that the port cannot be bound mpre than once.

**Comment by nicojanssens** [comment]
What's the current status of this issue?

I'm facing similar problems, my Cordova app doesn't receive UDP messages when running on an  iDevice. Chrome app works fine.

**Comment by Kobzol** [comment]
It turned out that I was sending with the UDP socket before it was properly initialized. I created a promise that resolves after the initialization (`chrome.sockets.udp.create` function) and do all the sends after that promise is resolved. After that it works fine, so it was a problem with my code. I'm binding the socket to "0.0.0.0" and port 0 (auto-select) before sending data through it.

**Comment by nicojanssens** [comment]
Thanks, @Kobzol.

It turned out that the root cause of my problem was slightly different from yours, but your suggestions definitely helped me squashing my bug.

**Comment by Smiral97** [comment]
> I'm having problems with receiving UDP sockets on iOS.
> I create a socket on iPhone, send a message, the other side receives it and sends a response to the phone's address (IP, port), but the callback registered with onReceive doesn't fire.
> The same code works without problems on Android.
> I tried setting the socket as persistent, that didn't help.
> Is there anything extra that has to be done for this to work?

Have you found the solution?I have a exact same problem.. HELP!

**Comment by Kobzol** [comment]
I described the solution in a comment above (https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp/issues/9#issuecomment-244291742). I was using the socket before it was initialized, you need to make sure that everything happens only after all callbacks are processed (initialization, port bind etc.). I also had some issues with broadcast, for that I needed to enable the broadcast flag on the socket.

**Comment by Smiral97** [comment]
But in my android device it is working perfectly.. here is my code.
![Screenshot 2019-12-24 at 3 42 33 PM](https://user-images.githubusercontent.com/59197939/71408418-28b8b480-2664-11ea-8592-284798a6e408.png)

code flow does not go to the onReceive method in ios.

**Comment by Smiral97** [comment]
> I described the solution in a comment above ([#9 (comment)](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp/issues/9#issuecomment-244291742)). I was using the socket before it was initialized, you need to make sure that everything happens only after all callbacks are processed (initialization, port bind etc.). I also had some issues with broadcast, for that I needed to enable the broadcast flag on the socket.

But in my android device it is working perfectly. Here is my code.

![Screenshot 2019-12-24 at 3 42 33 PM](https://user-images.githubusercontent.com/59197939/71408488-759c8b00-2664-11ea-9c78-22a9316d49ae.png)

code flow does not go in the onReceive method.

**Comment by Kobzol** [comment]
If you're setting the port to 0, that means that you can only pretty much receive broadcast packets (otherwise the other side wouldn't know which port to send to). In that case you have to enable broadcast (`chrome.sockets.udp.setBroadcast(sockId, true, callback)`) and only bind after the broadcast is enabled.
